application: salimsobieroj
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /email.py
  script: salimapp.application

- url: /(.*\.(html|css|js|gif|png|jpg))
  static_files: \1
  upload: (.*\.(html|css|js|gif|png|jpg))